# Generated by Django 2.0.5 on 2021-05-31 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckWeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usid', models.CharField(max_length=500)),
                ('img_path', models.CharField(max_length=500)),
                ('rslt', models.CharField(max_length=500)),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectadmin.DatatrainModel')),
            ],
        ),
    ]
