# Generated by Django 6.0.2 on 2026-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('aqi', models.FloatField()),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='WAQI', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('uname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='view_dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stn_code', models.CharField(max_length=300)),
                ('sampling_date', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('agency', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('so2', models.CharField(max_length=300)),
                ('no2', models.CharField(max_length=300)),
                ('rspm', models.CharField(max_length=300)),
                ('spm', models.CharField(max_length=300)),
                ('location_monitoring_station', models.CharField(max_length=300)),
                ('pm2_5', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
            ],
        ),
    ]
