# Generated by Django 6.0.2 on 2026-03-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20260309_2337'),
    ]

    operations = [
    ]
